versions:
  "0.9.0":
    released_at: 2026-01-05T08:00:00Z
    notes: Beta version
    matchers:
      - matcher_type: default
        severity: yellow
  "1.0.0":
    released_at: 2026-01-10T09:00:00Z
    notes: First stable release
    matchers:
      - matcher_type: default
        severity: green
  "1.0.1":
    released_at: 2026-01-12T14:00:00Z
    notes: Bugfix release
    matchers:
      - matcher_type: default
        severity: green
  "1.1.0":
    released_at: 2026-01-18T16:00:00Z
    notes: Feature release
    matchers:
      - matcher_type: country
        matcher_value: FR
        severity: yellow
      - matcher_type: default
        severity: green

