versions:
  "1.0.0":
    released_at: 2026-01-10T09:00:00Z
    matchers:
      - matcher_type: default
        severity: green
  "1.1.0":
    released_at: 2026-01-15T10:00:00Z
    matchers:
      - matcher_type: default
        severity: green

