versions:
  "1.0.0":
    released_at: 2026-01-10T09:00:00Z
    notes: Initial release
    matchers:
      - matcher_type: default
        severity: green
  "1.1.0":
    released_at: 2026-01-15T10:00:00Z
    notes: Feature update
    matchers:
      - matcher_type: country
        matcher_value: US
        severity: yellow
      - matcher_type: default
        severity: green
  "2.0.0":
    released_at: 2026-01-20T11:00:00Z
    notes: Major release
    matchers:
      - matcher_type: location_hash
        matcher_value: 5feceb66ffc86f38d952786c6d696c79c2dbc239dd4e91b46729d73a27fb57e9
        severity: red
      - matcher_type: country
        matcher_value: GB
        severity: yellow
      - matcher_type: default
        severity: green

